set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(FASTDIS_MINGW_PREFIX "x86_64-w64-mingw32" CACHE STRING "MinGW-w64 toolchain prefix")

find_program(FASTDIS_MINGW_C_COMPILER NAMES "${FASTDIS_MINGW_PREFIX}-gcc" REQUIRED)
find_program(FASTDIS_MINGW_CXX_COMPILER NAMES "${FASTDIS_MINGW_PREFIX}-g++" REQUIRED)
find_program(FASTDIS_MINGW_RC_COMPILER NAMES "${FASTDIS_MINGW_PREFIX}-windres" "windres" REQUIRED)

set(CMAKE_C_COMPILER "${FASTDIS_MINGW_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${FASTDIS_MINGW_CXX_COMPILER}")
set(CMAKE_RC_COMPILER "${FASTDIS_MINGW_RC_COMPILER}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
