#!/usr/bin/env python3
"""Generate slotted semantic PDU parser entry points for every DIS 6/7 PDU row."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

from generate_pdu_catalog import DEFAULT_DIS6, DEFAULT_DIS7, ROOT
from generate_typed_pdu_parsers import typed_rows


FULLY_DOMAIN_DECODED_ROWS = {
    (6, 1),
    (6, 2),
    (6, 3),
    (6, 4),
    (6, 13),
    (6, 14),
    (6, 15),
    (6, 16),
    (6, 17),
    (6, 18),
    (6, 19),
    (6, 20),
    (6, 21),
    (6, 22),
    (6, 24),
    (6, 25),
    (6, 26),
    (6, 27),
    (6, 23),
    (6, 28),
    (6, 29),
    (6, 32),
    (6, 31),
    (6, 30),
    (6, 11),
    (6, 12),
    (6, 51),
    (6, 52),
    (6, 53),
    (6, 54),
    (6, 55),
    (6, 56),
    (6, 57),
    (6, 58),
    (6, 59),
    (6, 60),
    (6, 61),
    (6, 62),
    (6, 64),
    (6, 65),
    (6, 66),
    (6, 67),
    (7, 1),
    (7, 2),
    (7, 3),
    (7, 4),
    (7, 13),
    (7, 14),
    (7, 15),
    (7, 16),
    (7, 17),
    (7, 18),
    (7, 19),
    (7, 20),
    (7, 21),
    (7, 22),
    (7, 24),
    (7, 25),
    (7, 26),
    (7, 27),
    (7, 23),
    (7, 29),
    (7, 32),
    (7, 31),
    (7, 30),
    (7, 11),
    (7, 12),
    (7, 51),
    (7, 52),
    (7, 53),
    (7, 54),
    (7, 55),
    (7, 56),
    (7, 57),
    (7, 58),
    (7, 59),
    (7, 60),
    (7, 61),
    (7, 62),
    (7, 65),
    (7, 66),
    (7, 67),
    (7, 68),
    (7, 69),
}


def semantic_rows(dis6: Path, dis7: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in typed_rows(dis6, dis7):
        key = (int(row["protocol_version"]), int(row["pdu_type"]))
        typed_semantic = bool(row["typed_semantic"])
        fully_domain_decoded = key in FULLY_DOMAIN_DECODED_ROWS
        if typed_semantic:
            semantic_level = "semantic_prefix"
        elif fully_domain_decoded:
            semantic_level = "semantic_decoded"
        else:
            semantic_level = "semantic_observation"
        semantic_class = str(row["parser_class"]).replace("Pdu", "SemanticPdu")
        if semantic_class == row["parser_class"]:
            semantic_class = f"{row['parser_class']}Semantic"
        rows.append(
            {
                **row,
                "semantic_class": semantic_class,
                "semantic_parser": True,
                "semantic_level": semantic_level,
                "fully_domain_decoded": fully_domain_decoded,
                "diagnostic_policy": (
                    "domain_prefix_available"
                    if typed_semantic
                    else "decoded_fixed_fields_available"
                    if fully_domain_decoded
                    else "typed observation preserves raw body and exposes schema/field metadata"
                ),
            }
        )
    return rows


def _descriptor_literal(row: dict[str, Any]) -> str:
    return (
        "    SemanticPduDescriptor("
        f"{row['protocol_version']}, {row['pdu_type']}, {row['protocol_family']}, "
        f"{row['standard_name']!r}, {row['standard_class_name']!r}, {row['semantic_class']!r}, "
        f"{row['parser_class']!r}, {row['family_name']!r}, {row['schema_status']!r}, "
        f"{row['catalog_status']!r}, {tuple(row['declared_fields'])!r}, {row['semantic_level']!r}, "
        f"{bool(row['fully_domain_decoded'])!r}),"
    )


def generate_python(rows: list[dict[str, Any]]) -> str:
    class_defs = "\n\n".join(
        f"@dataclass(frozen=True, slots=True)\nclass {row['semantic_class']}(SemanticPdu):\n    pass"
        for row in rows
    )
    descriptors = "\n".join(_descriptor_literal(row) for row in rows)
    class_map_entries = "\n".join(f"    {row['semantic_class']!r}: {row['semantic_class']}," for row in rows)
    return (
        '"""Generated slotted semantic DIS PDU parser entry points.\n\n'
        "Every standard DIS 6/7 PDU row gets a semantic parser class. Rows without\n"
        "full domain decoding are represented as explicit semantic observations\n"
        "with raw-body preservation and diagnostics.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "import struct\n"
        "from dataclasses import dataclass\n"
        "from types import MappingProxyType\n"
        "from typing import Mapping\n\n"
        "from .typed_pdus import TypedPdu, parse_typed_pdu, serialize_typed_pdu\n\n\n"
        "@dataclass(frozen=True, slots=True)\n"
        "class SemanticPduDescriptor:\n"
        "    protocol_version: int\n"
        "    pdu_type: int\n"
        "    protocol_family: int\n"
        "    standard_name: str\n"
        "    standard_class_name: str\n"
        "    semantic_class: str\n"
        "    typed_class: str\n"
        "    family_name: str\n"
        "    schema_status: str\n"
        "    catalog_status: str\n"
        "    declared_fields: tuple[str, ...]\n"
        "    semantic_level: str\n"
        "    fully_domain_decoded: bool\n\n\n"
        "@dataclass(frozen=True, slots=True)\n"
        "class SemanticPdu:\n"
        "    descriptor: SemanticPduDescriptor\n"
        "    typed: TypedPdu\n"
        "    semantic_fields: Mapping[str, object]\n"
        "    diagnostics: tuple[str, ...]\n\n"
        "    @property\n"
        "    def header(self):\n"
        "        return self.typed.header\n\n"
        "    @property\n"
        "    def packet(self) -> bytes:\n"
        "        return self.typed.packet\n\n"
        "    @property\n"
        "    def body(self) -> bytes:\n"
        "        return self.typed.body\n\n"
        "    @property\n"
        "    def semantic_level(self) -> str:\n"
        "        return self.descriptor.semantic_level\n\n\n"
        + class_defs
        + "\n\n\n"
        "SEMANTIC_PDU_DESCRIPTORS: tuple[SemanticPduDescriptor, ...] = (\n"
        + descriptors
        + "\n)\n\n"
        "_DESCRIPTORS_BY_KEY = {(item.protocol_version, item.pdu_type): item for item in SEMANTIC_PDU_DESCRIPTORS}\n"
        "_CLASS_BY_NAME: dict[str, type[SemanticPdu]] = {\n"
        + class_map_entries
        + "\n}\n\n\n"
        "def _entity_id(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    site, application, entity = struct.unpack_from('>HHH', body, offset)\n"
        "    return ({'site': int(site), 'application': int(application), 'entity': int(entity)}, offset + 6)\n\n\n"
        "def _event_id(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    site, application, event_number = struct.unpack_from('>HHH', body, offset)\n"
        "    return ({'site': int(site), 'application': int(application), 'event_number': int(event_number)}, offset + 6)\n\n\n"
        "def _entity_type(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    kind, domain, country, category, subcategory, specific, extra = struct.unpack_from('>BBHBBBB', body, offset)\n"
        "    return ({'kind': int(kind), 'domain': int(domain), 'country': int(country), 'category': int(category), 'subcategory': int(subcategory), 'specific': int(specific), 'extra': int(extra)}, offset + 8)\n\n\n"
        "def _vec3f(body: bytes, offset: int) -> tuple[dict[str, float], int]:\n"
        "    x, y, z = struct.unpack_from('>fff', body, offset)\n"
        "    return ({'x': float(x), 'y': float(y), 'z': float(z)}, offset + 12)\n\n\n"
        "def _vec3d(body: bytes, offset: int) -> tuple[dict[str, float], int]:\n"
        "    x, y, z = struct.unpack_from('>ddd', body, offset)\n"
        "    return ({'x': float(x), 'y': float(y), 'z': float(z)}, offset + 24)\n\n\n"
        "def _clock_time(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    hour, time_past_hour = struct.unpack_from('>II', body, offset)\n"
        "    return ({'hour': int(hour), 'time_past_hour': int(time_past_hour)}, offset + 8)\n\n\n"
        "def _munition_descriptor(body: bytes, offset: int) -> tuple[dict[str, object], int]:\n"
        "    munition_type, offset = _entity_type(body, offset)\n"
        "    warhead, fuse, quantity, rate = struct.unpack_from('>HHHH', body, offset)\n"
        "    return ({'munition_type': munition_type, 'warhead': int(warhead), 'fuse': int(fuse), 'quantity': int(quantity), 'rate': int(rate)}, offset + 8)\n\n\n"
        "def _radio_entity_type(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    entity_kind, domain, country, category, nomenclature_version, nomenclature = struct.unpack_from('>BBHBBH', body, offset)\n"
        "    return ({'entity_kind': int(entity_kind), 'domain': int(domain), 'country': int(country), 'category': int(category), 'nomenclature_version': int(nomenclature_version), 'nomenclature': int(nomenclature)}, offset + 8)\n\n\n"
        "def _modulation_type_dis6(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    spread_spectrum, major, detail, system = struct.unpack_from('>HHHH', body, offset)\n"
        "    return ({'spread_spectrum': int(spread_spectrum), 'major': int(major), 'detail': int(detail), 'system': int(system)}, offset + 8)\n\n\n"
        "def _modulation_type_dis7(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    spread_spectrum, major_modulation, detail, radio_system = struct.unpack_from('>HHHH', body, offset)\n"
        "    return ({'spread_spectrum': int(spread_spectrum), 'major_modulation': int(major_modulation), 'detail': int(detail), 'radio_system': int(radio_system)}, offset + 8)\n\n\n"
        "def _decode_create_remove_entity(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_create_remove_entity_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_start_resume(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    real_world_time, offset = _clock_time(body, offset)\n"
        "    simulation_time, offset = _clock_time(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'real_world_time': real_world_time,\n"
        "        'simulation_time': simulation_time,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_stop_freeze(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    real_world_time, offset = _clock_time(body, offset)\n"
        "    reason = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    frozen_behavior = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'real_world_time': real_world_time,\n"
        "        'reason': reason,\n"
        "        'frozen_behavior': frozen_behavior,\n"
        "        'padding1': padding1,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_acknowledge(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    acknowledge_flag = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    response_flag = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'acknowledge_flag': acknowledge_flag,\n"
        "        'response_flag': response_flag,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_start_resume_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    real_world_time, offset = _clock_time(body, offset)\n"
        "    simulation_time, offset = _clock_time(body, offset)\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'real_world_time': real_world_time,\n"
        "        'simulation_time': simulation_time,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_stop_freeze_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    real_world_time, offset = _clock_time(body, offset)\n"
        "    reason = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    frozen_behavior = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    required_reliablity_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'real_world_time': real_world_time,\n"
        "        'reason': reason,\n"
        "        'frozen_behavior': frozen_behavior,\n"
        "        'required_reliablity_service': required_reliablity_service,\n"
        "        'pad1': pad1,\n"
        "        'request_id': request_id,\n"
        "    })\n\n\n"
        "def _decode_acknowledge_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    return _decode_acknowledge(typed)\n\n\n"
        "def _decode_action_request(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    action_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'action_id': action_id,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_action_response(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    request_status = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'request_status': request_status,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_action_request_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    action_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'request_id': request_id,\n"
        "        'action_id': action_id,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_action_response_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    response_status = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'response_status': response_status,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_data_query(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    time_interval, offset = _clock_time(body, offset)\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'time_interval': time_interval,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_set_data(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    padding1 = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'padding1': padding1,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_event_report(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    event_type = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    padding1 = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'event_type': event_type,\n"
        "        'padding1': padding1,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_comment(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_data_query_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    time_interval, offset = _clock_time(body, offset)\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'request_id': request_id,\n"
        "        'time_interval': time_interval,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_set_data_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'request_id': request_id,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_data_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_event_report_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    event_type = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    pad1 = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_fixed_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    number_of_variable_datum_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    datum_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'event_type': event_type,\n"
        "        'pad1': pad1,\n"
        "        'number_of_fixed_datum_records': number_of_fixed_datum_records,\n"
        "        'number_of_variable_datum_records': number_of_variable_datum_records,\n"
        "        'datum_record_bytes': datum_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_comment_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    return _decode_comment(typed)\n\n\n"
        "def _decode_set_record_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_record_sets = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    record_set_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'number_of_record_sets': number_of_record_sets,\n"
        "        'record_set_bytes': record_set_bytes,\n"
        "    })\n\n\n"
        "def _decode_record_query_reliable(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    originating_entity_id, offset = _entity_id(body, offset)\n"
        "    receiving_entity_id, offset = _entity_id(body, offset)\n"
        "    request_id = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    required_reliability_service = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    pad2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    event_type = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    time, offset = _clock_time(body, offset)\n"
        "    number_of_records = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    record_id_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'originating_entity_id': originating_entity_id,\n"
        "        'receiving_entity_id': receiving_entity_id,\n"
        "        'request_id': request_id,\n"
        "        'required_reliability_service': required_reliability_service,\n"
        "        'pad1': pad1,\n"
        "        'pad2': pad2,\n"
        "        'event_type': event_type,\n"
        "        'time': time,\n"
        "        'number_of_records': number_of_records,\n"
        "        'record_id_bytes': record_id_bytes,\n"
        "    })\n\n\n"
        "def _decode_signal_dis6(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    entity_id, offset = _entity_id(body, offset)\n"
        "    radio_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    encoding_scheme = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    tdl_type = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    sample_rate = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    data_length = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    samples = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    data_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'entity_id': entity_id,\n"
        "        'radio_id': radio_id,\n"
        "        'encoding_scheme': encoding_scheme,\n"
        "        'tdl_type': tdl_type,\n"
        "        'sample_rate': sample_rate,\n"
        "        'data_length': data_length,\n"
        "        'samples': samples,\n"
        "        'data_bytes': data_bytes,\n"
        "    })\n\n\n"
        "def _decode_signal_dis7(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    encoding_scheme = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    tdl_type = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    sample_rate = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    data_length = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    samples = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    data_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'encoding_scheme': encoding_scheme,\n"
        "        'tdl_type': tdl_type,\n"
        "        'sample_rate': sample_rate,\n"
        "        'data_length': data_length,\n"
        "        'samples': samples,\n"
        "        'data_bytes': data_bytes,\n"
        "    })\n\n\n"
        "def _decode_intercom_signal_dis6(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    entity_id, offset = _entity_id(body, offset)\n"
        "    communications_device_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    encoding_scheme = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    tdl_type = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    sample_rate = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    data_length = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    samples = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    data_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'entity_id': entity_id,\n"
        "        'communications_device_id': communications_device_id,\n"
        "        'encoding_scheme': encoding_scheme,\n"
        "        'tdl_type': tdl_type,\n"
        "        'sample_rate': sample_rate,\n"
        "        'data_length': data_length,\n"
        "        'samples': samples,\n"
        "        'data_bytes': data_bytes,\n"
        "    })\n\n\n"
        "def _decode_intercom_signal_dis7(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    entity_id, offset = _entity_id(body, offset)\n"
        "    communications_device_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    encoding_scheme = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    tdl_type = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    sample_rate = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    data_length = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    samples = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    data_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'entity_id': entity_id,\n"
        "        'communications_device_id': communications_device_id,\n"
        "        'encoding_scheme': encoding_scheme,\n"
        "        'tdl_type': tdl_type,\n"
        "        'sample_rate': sample_rate,\n"
        "        'data_length': data_length,\n"
        "        'samples': samples,\n"
        "        'data_bytes': data_bytes,\n"
        "    })\n\n\n"
        "def _decode_intercom_control(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    control_type = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    communications_channel_type = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    source_entity_id, offset = _entity_id(body, offset)\n"
        "    source_communications_device_id = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    source_line_id = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    transmit_priority = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    transmit_line_state = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    command = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    master_entity_id, offset = _entity_id(body, offset)\n"
        "    master_communications_device_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    intercom_parameters_length = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    intercom_parameters_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'control_type': control_type,\n"
        "        'communications_channel_type': communications_channel_type,\n"
        "        'source_entity_id': source_entity_id,\n"
        "        'source_communications_device_id': source_communications_device_id,\n"
        "        'source_line_id': source_line_id,\n"
        "        'transmit_priority': transmit_priority,\n"
        "        'transmit_line_state': transmit_line_state,\n"
        "        'command': command,\n"
        "        'master_entity_id': master_entity_id,\n"
        "        'master_communications_device_id': master_communications_device_id,\n"
        "        'intercom_parameters_length': intercom_parameters_length,\n"
        "        'intercom_parameters_bytes': intercom_parameters_bytes,\n"
        "    })\n\n\n"
        "def _decode_receiver_dis6(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    entity_id, offset = _entity_id(body, offset)\n"
        "    radio_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    receiver_state = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    padding1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    received_power = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    transmitter_entity_id, offset = _entity_id(body, offset)\n"
        "    transmitter_radio_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'entity_id': entity_id,\n"
        "        'radio_id': radio_id,\n"
        "        'receiver_state': receiver_state,\n"
        "        'padding1': padding1,\n"
        "        'received_power': received_power,\n"
        "        'transmitter_entity_id': transmitter_entity_id,\n"
        "        'transmitter_radio_id': transmitter_radio_id,\n"
        "    })\n\n\n"
        "def _decode_receiver_dis7(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    receiver_state = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    padding1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    received_power = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    transmitter_entity_id, offset = _entity_id(body, offset)\n"
        "    transmitter_radio_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'receiver_state': receiver_state,\n"
        "        'padding1': padding1,\n"
        "        'received_power': received_power,\n"
        "        'transmitter_entity_id': transmitter_entity_id,\n"
        "        'transmitter_radio_id': transmitter_radio_id,\n"
        "    })\n\n\n"
        "def _decode_transmitter_dis6(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    entity_id, offset = _entity_id(body, offset)\n"
        "    radio_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    radio_entity_type, offset = _radio_entity_type(body, offset)\n"
        "    transmit_state = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    input_source = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    antenna_location, offset = _vec3d(body, offset)\n"
        "    relative_antenna_location, offset = _vec3f(body, offset)\n"
        "    antenna_pattern_type = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    antenna_pattern_count = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    frequency = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    transmit_frequency_bandwidth = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    power = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    modulation_type, offset = _modulation_type_dis6(body, offset)\n"
        "    crypto_system = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    crypto_key_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    modulation_parameter_count = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding2 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    padding3 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    variable_payload_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'entity_id': entity_id,\n"
        "        'radio_id': radio_id,\n"
        "        'radio_entity_type': radio_entity_type,\n"
        "        'transmit_state': transmit_state,\n"
        "        'input_source': input_source,\n"
        "        'padding1': padding1,\n"
        "        'antenna_location': antenna_location,\n"
        "        'relative_antenna_location': relative_antenna_location,\n"
        "        'antenna_pattern_type': antenna_pattern_type,\n"
        "        'antenna_pattern_count': antenna_pattern_count,\n"
        "        'frequency': frequency,\n"
        "        'transmit_frequency_bandwidth': transmit_frequency_bandwidth,\n"
        "        'power': power,\n"
        "        'modulation_type': modulation_type,\n"
        "        'crypto_system': crypto_system,\n"
        "        'crypto_key_id': crypto_key_id,\n"
        "        'modulation_parameter_count': modulation_parameter_count,\n"
        "        'padding2': padding2,\n"
        "        'padding3': padding3,\n"
        "        'variable_payload_bytes': variable_payload_bytes,\n"
        "    })\n\n\n"
        "def _decode_transmitter_dis7(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    radio_reference_id, offset = _entity_id(body, offset)\n"
        "    radio_number = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    radio_entity_type, offset = _entity_type(body, offset)\n"
        "    transmit_state = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    input_source = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    variable_transmitter_parameter_count = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    antenna_location, offset = _vec3d(body, offset)\n"
        "    relative_antenna_location, offset = _vec3f(body, offset)\n"
        "    antenna_pattern_type = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    antenna_pattern_count = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    frequency = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    transmit_frequency_bandwidth = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    power = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    modulation_type, offset = _modulation_type_dis7(body, offset)\n"
        "    crypto_system = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    crypto_key_id = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    modulation_parameter_count = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding2 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    padding3 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    variable_payload_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'radio_reference_id': radio_reference_id,\n"
        "        'radio_number': radio_number,\n"
        "        'radio_entity_type': radio_entity_type,\n"
        "        'transmit_state': transmit_state,\n"
        "        'input_source': input_source,\n"
        "        'variable_transmitter_parameter_count': variable_transmitter_parameter_count,\n"
        "        'antenna_location': antenna_location,\n"
        "        'relative_antenna_location': relative_antenna_location,\n"
        "        'antenna_pattern_type': antenna_pattern_type,\n"
        "        'antenna_pattern_count': antenna_pattern_count,\n"
        "        'frequency': frequency,\n"
        "        'transmit_frequency_bandwidth': transmit_frequency_bandwidth,\n"
        "        'power': power,\n"
        "        'modulation_type': modulation_type,\n"
        "        'crypto_system': crypto_system,\n"
        "        'crypto_key_id': crypto_key_id,\n"
        "        'modulation_parameter_count': modulation_parameter_count,\n"
        "        'padding2': padding2,\n"
        "        'padding3': padding3,\n"
        "        'variable_payload_bytes': variable_payload_bytes,\n"
        "    })\n\n\n"
        "def _decode_designator(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    designating_entity_id, offset = _entity_id(body, offset)\n"
        "    code_name = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    designated_entity_id, offset = _entity_id(body, offset)\n"
        "    designator_code = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    designator_power = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    designator_wavelength = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    designator_spot_wrt_designated, offset = _vec3f(body, offset)\n"
        "    designator_spot_location, offset = _vec3d(body, offset)\n"
        "    dead_reckoning_algorithm = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    padding2 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    entity_linear_acceleration, offset = _vec3f(body, offset)\n"
        "    return MappingProxyType({\n"
        "        'designating_entity_id': designating_entity_id,\n"
        "        'code_name': code_name,\n"
        "        'designated_entity_id': designated_entity_id,\n"
        "        'designator_code': designator_code,\n"
        "        'designator_power': designator_power,\n"
        "        'designator_wavelength': designator_wavelength,\n"
        "        'designator_spot_wrt_designated': designator_spot_wrt_designated,\n"
        "        'designator_spot_location': designator_spot_location,\n"
        "        'dead_reckoning_algorithm': dead_reckoning_algorithm,\n"
        "        'padding1': padding1,\n"
        "        'padding2': padding2,\n"
        "        'entity_linear_acceleration': entity_linear_acceleration,\n"
        "    })\n\n\n"
        "def _decode_emitter_system_dis6(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    emitter_name, function, emitter_id_number = struct.unpack_from('>HBB', body, offset)\n"
        "    return ({'emitter_name': int(emitter_name), 'function': int(function), 'emitter_id_number': int(emitter_id_number)}, offset + 4)\n\n\n"
        "def _decode_emitter_system_dis7(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    emitter_name, emitter_function, emitter_id_number = struct.unpack_from('>HBB', body, offset)\n"
        "    return ({'emitter_name': int(emitter_name), 'emitter_function': int(emitter_function), 'emitter_id_number': int(emitter_id_number)}, offset + 4)\n\n\n"
        "def _decode_system_id_dis6(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    system_type, system_name, system_mode, change_options = struct.unpack_from('>HHBB', body, offset)\n"
        "    return ({'system_type': int(system_type), 'system_name': int(system_name), 'system_mode': int(system_mode), 'change_options': int(change_options)}, offset + 6)\n\n\n"
        "def _decode_iff_fundamental_data_dis6(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    system_status, alternate_parameter4, information_layers, modifier = struct.unpack_from('>BBBB', body, offset)\n"
        "    offset += 4\n"
        "    parameter1, parameter2, parameter3, parameter4, parameter5, parameter6 = struct.unpack_from('>HHHHHH', body, offset)\n"
        "    offset += 12\n"
        "    return ({'system_status': int(system_status), 'alternate_parameter4': int(alternate_parameter4), 'information_layers': int(information_layers), 'modifier': int(modifier), 'parameter1': int(parameter1), 'parameter2': int(parameter2), 'parameter3': int(parameter3), 'parameter4': int(parameter4), 'parameter5': int(parameter5), 'parameter6': int(parameter6)}, offset)\n\n\n"
        "def _decode_shaft_rpms_dis6(body: bytes, offset: int) -> tuple[dict[str, float], int]:\n"
        "    current_shaft_rpms, ordered_shaft_rpms = struct.unpack_from('>hh', body, offset)\n"
        "    offset += 4\n"
        "    shaft_rpm_rate_of_change = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    return ({'current_shaft_rpms': int(current_shaft_rpms), 'ordered_shaft_rpms': int(ordered_shaft_rpms), 'shaft_rpm_rate_of_change': shaft_rpm_rate_of_change}, offset)\n\n\n"
        "def _decode_apa_data_dis6(body: bytes, offset: int) -> tuple[dict[str, int], int]:\n"
        "    parameter_index = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    parameter_value = int(struct.unpack_from('>h', body, offset)[0])\n"
        "    offset += 2\n"
        "    return ({'parameter_index': parameter_index, 'parameter_value': parameter_value}, offset)\n\n\n"
        "def _decode_electromagnetic_emission_dis6(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    emitting_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    state_update_indicator = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_systems = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding_for_emissions_pdu = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    systems_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'emitting_entity_id': emitting_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'state_update_indicator': state_update_indicator,\n"
        "        'number_of_systems': number_of_systems,\n"
        "        'padding_for_emissions_pdu': padding_for_emissions_pdu,\n"
        "        'systems_bytes': systems_bytes,\n"
        "    })\n\n\n"
        "def _decode_electromagnetic_emission_dis7(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    emitting_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    state_update_indicator = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_systems = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding_for_emissions_pdu = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    system_data_length = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_beams = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    emitter_system, offset = _decode_emitter_system_dis7(body, offset)\n"
        "    location, offset = _vec3f(body, offset)\n"
        "    systems_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'emitting_entity_id': emitting_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'state_update_indicator': state_update_indicator,\n"
        "        'number_of_systems': number_of_systems,\n"
        "        'padding_for_emissions_pdu': padding_for_emissions_pdu,\n"
        "        'system_data_length': system_data_length,\n"
        "        'number_of_beams': number_of_beams,\n"
        "        'emitter_system': emitter_system,\n"
        "        'location': location,\n"
        "        'systems_bytes': systems_bytes,\n"
        "    })\n\n\n"
        "def _decode_iff_atc_navaids_dis6(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    emitting_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    location, offset = _vec3f(body, offset)\n"
        "    system_id, offset = _decode_system_id_dis6(body, offset)\n"
        "    pad2 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    fundamental_parameters, offset = _decode_iff_fundamental_data_dis6(body, offset)\n"
        "    return MappingProxyType({\n"
        "        'emitting_entity_id': emitting_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'location': location,\n"
        "        'system_id': system_id,\n"
        "        'pad2': pad2,\n"
        "        'fundamental_parameters': fundamental_parameters,\n"
        "    })\n\n\n"
        "def _decode_underwater_acoustic(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    emitting_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    state_change_indicator = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    pad = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    passive_parameter_index = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    propulsion_plant_configuration = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_shafts = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_apas = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    number_of_ua_emitter_systems = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    shaft_rpms = []\n"
        "    for _ in range(number_of_shafts):\n"
        "        record, offset = _decode_shaft_rpms_dis6(body, offset)\n"
        "        shaft_rpms.append(record)\n"
        "    apa_data = []\n"
        "    for _ in range(number_of_apas):\n"
        "        record, offset = _decode_apa_data_dis6(body, offset)\n"
        "        apa_data.append(record)\n"
        "    emitter_systems_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'emitting_entity_id': emitting_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'state_change_indicator': state_change_indicator,\n"
        "        'pad': pad,\n"
        "        'passive_parameter_index': passive_parameter_index,\n"
        "        'propulsion_plant_configuration': propulsion_plant_configuration,\n"
        "        'number_of_shafts': number_of_shafts,\n"
        "        'number_of_apas': number_of_apas,\n"
        "        'number_of_ua_emitter_systems': number_of_ua_emitter_systems,\n"
        "        'shaft_rpms': tuple(shaft_rpms),\n"
        "        'apa_data': tuple(apa_data),\n"
        "        'emitter_systems_bytes': emitter_systems_bytes,\n"
        "    })\n\n\n"
        "def _decode_sees(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    orginating_entity_id, offset = _entity_id(body, offset)\n"
        "    infrared_signature_representation_index = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    acoustic_signature_representation_index = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    radar_cross_section_signature_representation_index = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    number_of_propulsion_systems = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    number_of_vectoring_nozzle_systems = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    propulsion_system_data = []\n"
        "    for _ in range(number_of_propulsion_systems):\n"
        "        power_setting = float(struct.unpack_from('>f', body, offset)[0])\n"
        "        offset += 4\n"
        "        engine_rpm = float(struct.unpack_from('>f', body, offset)[0])\n"
        "        offset += 4\n"
        "        propulsion_system_data.append({'power_setting': power_setting, 'engine_rpm': engine_rpm})\n"
        "    vectoring_system_data = []\n"
        "    for _ in range(number_of_vectoring_nozzle_systems):\n"
        "        horizontal_deflection_angle = float(struct.unpack_from('>f', body, offset)[0])\n"
        "        offset += 4\n"
        "        vertical_deflection_angle = float(struct.unpack_from('>f', body, offset)[0])\n"
        "        offset += 4\n"
        "        vectoring_system_data.append({'horizontal_deflection_angle': horizontal_deflection_angle, 'vertical_deflection_angle': vertical_deflection_angle})\n"
        "    return MappingProxyType({\n"
        "        'orginating_entity_id': orginating_entity_id,\n"
        "        'infrared_signature_representation_index': infrared_signature_representation_index,\n"
        "        'acoustic_signature_representation_index': acoustic_signature_representation_index,\n"
        "        'radar_cross_section_signature_representation_index': radar_cross_section_signature_representation_index,\n"
        "        'number_of_propulsion_systems': number_of_propulsion_systems,\n"
        "        'number_of_vectoring_nozzle_systems': number_of_vectoring_nozzle_systems,\n"
        "        'propulsion_system_data': tuple(propulsion_system_data),\n"
        "        'vectoring_system_data': tuple(vectoring_system_data),\n"
        "    })\n\n\n"
        "def _decode_fire(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    firing_entity_id, offset = _entity_id(body, offset)\n"
        "    target_entity_id, offset = _entity_id(body, offset)\n"
        "    munition_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    fire_mission_index = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    world_location, offset = _vec3d(body, offset)\n"
        "    munition_descriptor, offset = _munition_descriptor(body, offset)\n"
        "    velocity, offset = _vec3f(body, offset)\n"
        "    range_to_target_m = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'firing_entity_id': firing_entity_id,\n"
        "        'target_entity_id': target_entity_id,\n"
        "        'munition_entity_id': munition_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'fire_mission_index': fire_mission_index,\n"
        "        'world_location': world_location,\n"
        "        'munition_descriptor': munition_descriptor,\n"
        "        'velocity': velocity,\n"
        "        'range_to_target_m': range_to_target_m,\n"
        "    })\n\n\n"
        "def _decode_collision(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    issuing_entity_id, offset = _entity_id(body, offset)\n"
        "    colliding_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    collision_type = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    velocity, offset = _vec3f(body, offset)\n"
        "    mass_kg = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    location, offset = _vec3f(body, offset)\n"
        "    return MappingProxyType({\n"
        "        'issuing_entity_id': issuing_entity_id,\n"
        "        'colliding_entity_id': colliding_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'collision_type': collision_type,\n"
        "        'padding': padding,\n"
        "        'velocity': velocity,\n"
        "        'mass_kg': mass_kg,\n"
        "        'location': location,\n"
        "    })\n\n\n"
        "def _decode_detonation(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    firing_entity_id, offset = _entity_id(body, offset)\n"
        "    target_entity_id, offset = _entity_id(body, offset)\n"
        "    exploding_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    velocity, offset = _vec3f(body, offset)\n"
        "    world_location, offset = _vec3d(body, offset)\n"
        "    munition_descriptor, offset = _munition_descriptor(body, offset)\n"
        "    location_in_entity_coordinates, offset = _vec3f(body, offset)\n"
        "    detonation_result = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    variable_parameter_count = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    variable_parameter_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'firing_entity_id': firing_entity_id,\n"
        "        'target_entity_id': target_entity_id,\n"
        "        'exploding_entity_id': exploding_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'velocity': velocity,\n"
        "        'world_location': world_location,\n"
        "        'munition_descriptor': munition_descriptor,\n"
        "        'location_in_entity_coordinates': location_in_entity_coordinates,\n"
        "        'detonation_result': detonation_result,\n"
        "        'variable_parameter_count': variable_parameter_count,\n"
        "        'padding': padding,\n"
        "        'variable_parameter_bytes': variable_parameter_bytes,\n"
        "    })\n\n\n"
        "def _decode_directed_energy_fire(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    firing_entity_id, offset = _entity_id(body, offset)\n"
        "    target_entity_id, offset = _entity_id(body, offset)\n"
        "    munition_type, offset = _entity_type(body, offset)\n"
        "    shot_start_time, offset = _clock_time(body, offset)\n"
        "    cumulative_shot_time_s = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    aperture_emitter_location, offset = _vec3f(body, offset)\n"
        "    aperture_diameter_m = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    wavelength_m = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    peak_irradiance_w_m2 = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    pulse_repetition_frequency_hz = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    pulse_width = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    flags = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    pulse_shape = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding1 = int(struct.unpack_from('>B', body, offset)[0])\n"
        "    offset += 1\n"
        "    padding2 = int(struct.unpack_from('>I', body, offset)[0])\n"
        "    offset += 4\n"
        "    padding3 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    number_of_de_records = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    de_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'firing_entity_id': firing_entity_id,\n"
        "        'target_entity_id': target_entity_id,\n"
        "        'munition_type': munition_type,\n"
        "        'shot_start_time': shot_start_time,\n"
        "        'cumulative_shot_time_s': cumulative_shot_time_s,\n"
        "        'aperture_emitter_location': aperture_emitter_location,\n"
        "        'aperture_diameter_m': aperture_diameter_m,\n"
        "        'wavelength_m': wavelength_m,\n"
        "        'peak_irradiance_w_m2': peak_irradiance_w_m2,\n"
        "        'pulse_repetition_frequency_hz': pulse_repetition_frequency_hz,\n"
        "        'pulse_width': pulse_width,\n"
        "        'flags': flags,\n"
        "        'pulse_shape': pulse_shape,\n"
        "        'padding1': padding1,\n"
        "        'padding2': padding2,\n"
        "        'padding3': padding3,\n"
        "        'number_of_de_records': number_of_de_records,\n"
        "        'de_record_bytes': de_record_bytes,\n"
        "    })\n\n\n"
        "def _decode_collision_elastic(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    issuing_entity_id, offset = _entity_id(body, offset)\n"
        "    colliding_entity_id, offset = _entity_id(body, offset)\n"
        "    event_id, offset = _event_id(body, offset)\n"
        "    padding = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    contact_velocity, offset = _vec3f(body, offset)\n"
        "    mass_kg = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    offset += 4\n"
        "    location, offset = _vec3f(body, offset)\n"
        "    tensor = struct.unpack_from('>ffffff', body, offset)\n"
        "    offset += 24\n"
        "    unit_surface_normal, offset = _vec3f(body, offset)\n"
        "    coefficient_of_restitution = float(struct.unpack_from('>f', body, offset)[0])\n"
        "    return MappingProxyType({\n"
        "        'issuing_entity_id': issuing_entity_id,\n"
        "        'colliding_entity_id': colliding_entity_id,\n"
        "        'event_id': event_id,\n"
        "        'padding': padding,\n"
        "        'contact_velocity': contact_velocity,\n"
        "        'mass_kg': mass_kg,\n"
        "        'location': location,\n"
        "        'collision_tensor': {\n"
        "            'xx': float(tensor[0]),\n"
        "            'xy': float(tensor[1]),\n"
        "            'xz': float(tensor[2]),\n"
        "            'yy': float(tensor[3]),\n"
        "            'yz': float(tensor[4]),\n"
        "            'zz': float(tensor[5]),\n"
        "        },\n"
        "        'unit_surface_normal': unit_surface_normal,\n"
        "        'coefficient_of_restitution': coefficient_of_restitution,\n"
        "    })\n\n\n"
        "def _decode_entity_damage_status(typed: TypedPdu) -> Mapping[str, object]:\n"
        "    body = typed.body\n"
        "    offset = 0\n"
        "    firing_entity_id, offset = _entity_id(body, offset)\n"
        "    target_entity_id, offset = _entity_id(body, offset)\n"
        "    damaged_entity_id, offset = _entity_id(body, offset)\n"
        "    padding1 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    padding2 = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    number_of_damage_description = int(struct.unpack_from('>H', body, offset)[0])\n"
        "    offset += 2\n"
        "    damage_description_record_bytes = body[offset:]\n"
        "    return MappingProxyType({\n"
        "        'firing_entity_id': firing_entity_id,\n"
        "        'target_entity_id': target_entity_id,\n"
        "        'damaged_entity_id': damaged_entity_id,\n"
        "        'padding1': padding1,\n"
        "        'padding2': padding2,\n"
        "        'number_of_damage_description': number_of_damage_description,\n"
        "        'damage_description_record_bytes': damage_description_record_bytes,\n"
        "    })\n\n\n"
        "_SEMANTIC_DECODERS = {\n"
        "    (6, 11): _decode_create_remove_entity,\n"
        "    (6, 12): _decode_create_remove_entity,\n"
        "    (6, 13): _decode_start_resume,\n"
        "    (6, 14): _decode_stop_freeze,\n"
        "    (6, 15): _decode_acknowledge,\n"
        "    (6, 16): _decode_action_request,\n"
        "    (6, 17): _decode_action_response,\n"
        "    (6, 18): _decode_data_query,\n"
        "    (6, 19): _decode_set_data,\n"
        "    (6, 20): _decode_set_data,\n"
        "    (6, 21): _decode_event_report,\n"
        "    (6, 22): _decode_comment,\n"
        "    (6, 23): _decode_electromagnetic_emission_dis6,\n"
        "    (6, 24): _decode_designator,\n"
        "    (6, 25): _decode_transmitter_dis6,\n"
        "    (6, 26): _decode_signal_dis6,\n"
        "    (6, 27): _decode_receiver_dis6,\n"
        "    (6, 28): _decode_iff_atc_navaids_dis6,\n"
        "    (6, 29): _decode_underwater_acoustic,\n"
        "    (6, 30): _decode_sees,\n"
        "    (6, 2): _decode_fire,\n"
        "    (6, 3): _decode_detonation,\n"
        "    (6, 4): _decode_collision,\n"
        "    (6, 31): _decode_intercom_signal_dis6,\n"
        "    (6, 32): _decode_intercom_control,\n"
        "    (6, 51): _decode_create_remove_entity_reliable,\n"
        "    (6, 52): _decode_create_remove_entity_reliable,\n"
        "    (6, 53): _decode_start_resume_reliable,\n"
        "    (6, 54): _decode_stop_freeze_reliable,\n"
        "    (6, 55): _decode_acknowledge_reliable,\n"
        "    (6, 56): _decode_action_request_reliable,\n"
        "    (6, 57): _decode_action_response_reliable,\n"
        "    (6, 58): _decode_data_query_reliable,\n"
        "    (6, 59): _decode_set_data_reliable,\n"
        "    (6, 60): _decode_data_reliable,\n"
        "    (6, 61): _decode_event_report_reliable,\n"
        "    (6, 62): _decode_comment_reliable,\n"
        "    (6, 64): _decode_set_record_reliable,\n"
        "    (6, 65): _decode_record_query_reliable,\n"
        "    (6, 66): _decode_collision_elastic,\n"
        "    (7, 11): _decode_create_remove_entity,\n"
        "    (7, 12): _decode_create_remove_entity,\n"
        "    (7, 13): _decode_start_resume,\n"
        "    (7, 14): _decode_stop_freeze,\n"
        "    (7, 15): _decode_acknowledge,\n"
        "    (7, 16): _decode_action_request,\n"
        "    (7, 17): _decode_action_response,\n"
        "    (7, 18): _decode_data_query,\n"
        "    (7, 19): _decode_set_data,\n"
        "    (7, 20): _decode_set_data,\n"
        "    (7, 21): _decode_event_report,\n"
        "    (7, 22): _decode_comment,\n"
        "    (7, 23): _decode_electromagnetic_emission_dis7,\n"
        "    (7, 24): _decode_designator,\n"
        "    (7, 25): _decode_transmitter_dis7,\n"
        "    (7, 26): _decode_signal_dis7,\n"
        "    (7, 27): _decode_receiver_dis7,\n"
        "    (7, 29): _decode_underwater_acoustic,\n"
        "    (7, 30): _decode_sees,\n"
        "    (7, 2): _decode_fire,\n"
        "    (7, 3): _decode_detonation,\n"
        "    (7, 4): _decode_collision,\n"
        "    (7, 31): _decode_intercom_signal_dis7,\n"
        "    (7, 32): _decode_intercom_control,\n"
        "    (7, 51): _decode_create_remove_entity_reliable,\n"
        "    (7, 52): _decode_create_remove_entity_reliable,\n"
        "    (7, 53): _decode_start_resume_reliable,\n"
        "    (7, 54): _decode_stop_freeze_reliable,\n"
        "    (7, 55): _decode_acknowledge_reliable,\n"
        "    (7, 56): _decode_action_request_reliable,\n"
        "    (7, 57): _decode_action_response_reliable,\n"
        "    (7, 58): _decode_data_query_reliable,\n"
        "    (7, 59): _decode_set_data_reliable,\n"
        "    (7, 60): _decode_data_reliable,\n"
        "    (7, 61): _decode_event_report_reliable,\n"
        "    (7, 62): _decode_comment_reliable,\n"
        "    (7, 65): _decode_record_query_reliable,\n"
        "    (7, 66): _decode_collision_elastic,\n"
        "    (7, 68): _decode_directed_energy_fire,\n"
        "    (7, 69): _decode_entity_damage_status,\n"
        "}\n\n\n"
        "def find_semantic_pdu_descriptor(protocol_version: int, pdu_type: int) -> SemanticPduDescriptor | None:\n"
        "    return _DESCRIPTORS_BY_KEY.get((protocol_version, pdu_type))\n\n\n"
        "def _semantic_fields(descriptor: SemanticPduDescriptor, typed: TypedPdu) -> tuple[Mapping[str, object], str | None]:\n"
        "    fields = {\n"
        "        'protocol_version': typed.header[0],\n"
        "        'exercise_id': typed.header[1],\n"
        "        'pdu_type': typed.header[2],\n"
        "        'protocol_family': typed.header[3],\n"
        "        'timestamp': typed.header[4],\n"
        "        'declared_length': typed.header[5],\n"
        "        'standard_name': descriptor.standard_name,\n"
        "        'standard_class_name': descriptor.standard_class_name,\n"
        "        'schema_status': descriptor.schema_status,\n"
        "        'catalog_status': descriptor.catalog_status,\n"
        "        'declared_fields': descriptor.declared_fields,\n"
        "        'raw_body_size': len(typed.body),\n"
        "        'raw_body': typed.body,\n"
        "        'typed_parse_level': typed.parse_level,\n"
        "        'fully_domain_decoded': descriptor.fully_domain_decoded,\n"
        "    }\n"
        "    decoder = _SEMANTIC_DECODERS.get((typed.header[0], typed.header[2]))\n"
        "    if decoder is not None:\n"
        "        try:\n"
        "            decoded_fields = decoder(typed)\n"
        "        except (IndexError, ValueError, struct.error) as exc:\n"
        "            fields['semantic_decode_status'] = 'decode_error'\n"
        "            fields['semantic_decode_error'] = str(exc)\n"
        "            fields['semantic_decode_error_type'] = type(exc).__name__\n"
        "            return MappingProxyType(fields), f'semantic decoder failed: {type(exc).__name__}: {exc}'\n"
        "        fields['semantic_decode_status'] = 'decoded'\n"
        "        fields.update(decoded_fields)\n"
        "    elif descriptor.semantic_level == 'semantic_prefix':\n"
        "        fields['semantic_prefix_available'] = True\n"
        "        fields['semantic_decode_status'] = 'prefix'\n"
        "    else:\n"
        "        fields['semantic_decode_status'] = 'observation'\n"
        "    return MappingProxyType(fields), None\n\n\n"
        "def _diagnostics(descriptor: SemanticPduDescriptor, *, decode_error: str | None = None) -> tuple[str, ...]:\n"
        "    if decode_error is not None:\n"
        "        return (decode_error, f'schema_status={descriptor.schema_status}')\n"
        "    if descriptor.semantic_level == 'semantic_decoded':\n"
        "        return ('full domain decode available',)\n"
        "    if descriptor.semantic_level == 'semantic_prefix':\n"
        "        return ('semantic prefix parser available',)\n"
        "    return (\n"
        "        'semantic observation parser: full domain semantics not yet implemented',\n"
        "        f'schema_status={descriptor.schema_status}',\n"
        "    )\n\n\n"
        "def parse_semantic_pdu(data: bytes | bytearray | memoryview, *, strict: bool = True) -> SemanticPdu | None:\n"
        "    typed = parse_typed_pdu(data, strict=strict)\n"
        "    if typed is None:\n"
        "        return None\n"
        "    descriptor = find_semantic_pdu_descriptor(typed.header[0], typed.header[2])\n"
        "    if descriptor is None:\n"
        "        if strict:\n"
        "            raise ValueError(f'unknown DIS PDU type {typed.header[2]} for protocol version {typed.header[0]}')\n"
        "        return None\n"
        "    cls = _CLASS_BY_NAME[descriptor.semantic_class]\n"
        "    semantic_fields, decode_error = _semantic_fields(descriptor, typed)\n"
        "    return cls(\n"
        "        descriptor=descriptor,\n"
        "        typed=typed,\n"
        "        semantic_fields=semantic_fields,\n"
        "        diagnostics=_diagnostics(descriptor, decode_error=decode_error),\n"
        "    )\n\n\n"
        "def serialize_semantic_pdu(view: SemanticPdu) -> bytes:\n"
        "    if not isinstance(view, SemanticPdu):\n"
        "        raise TypeError('serialize_semantic_pdu expects a SemanticPdu')\n"
        "    return serialize_typed_pdu(view.typed)\n\n\n"
        "def parse_many_semantic(packets: list[bytes] | tuple[bytes, ...], *, strict: bool = False) -> list[SemanticPdu]:\n"
        "    out: list[SemanticPdu] = []\n"
        "    for packet in packets:\n"
        "        view = parse_semantic_pdu(packet, strict=strict)\n"
        "        if view is not None:\n"
        "            out.append(view)\n"
        "    return out\n\n\n"
        "SEMANTIC_PDU_PARSERS = {(item.protocol_version, item.pdu_type): parse_semantic_pdu for item in SEMANTIC_PDU_DESCRIPTORS}\n"
        "SEMANTIC_PDU_SERIALIZERS = {(item.protocol_version, item.pdu_type): serialize_semantic_pdu for item in SEMANTIC_PDU_DESCRIPTORS}\n"
    )


def generate_manifest(rows: list[dict[str, Any]]) -> str:
    payload = {
        "schema": "fastdis.semantic_pdu_parser_manifest.v1",
        "policy": {
            "semantic_parser": "Every standard DIS 6/7 PDU row has a generated semantic parser entry point.",
            "semantic_observation": "Rows without full domain decoding produce explicit semantic observations with diagnostics.",
            "semantic_prefix": "Rows with current typed semantic support expose semantic-prefix availability.",
            "semantic_decoded": "Rows with fixed-field semantic decoders expose decoded domain fields beyond metadata-only observations.",
        },
        "summary": {
            "records": len(rows),
            "semantic_parsers": sum(1 for row in rows if row["semantic_parser"]),
            "semantic_observation": sum(1 for row in rows if row["semantic_level"] == "semantic_observation"),
            "semantic_prefix": sum(1 for row in rows if row["semantic_level"] == "semantic_prefix"),
            "semantic_decoded": sum(1 for row in rows if row["semantic_level"] == "semantic_decoded"),
            "fully_domain_decoded": sum(1 for row in rows if row["fully_domain_decoded"]),
        },
        "records": rows,
    }
    return json.dumps(payload, indent=2) + "\n"


def generate_markdown(rows: list[dict[str, Any]]) -> str:
    semantic_parsers = sum(1 for row in rows if row["semantic_parser"])
    semantic_observation = sum(1 for row in rows if row["semantic_level"] == "semantic_observation")
    semantic_prefix = sum(1 for row in rows if row["semantic_level"] == "semantic_prefix")
    semantic_decoded = sum(1 for row in rows if row["semantic_level"] == "semantic_decoded")
    fully_domain_decoded = sum(1 for row in rows if row["fully_domain_decoded"])
    lines = [
        "# Semantic PDU Coverage",
        "",
        "FastDIS generates semantic parser entry points for every standard DIS 6/7 PDU row.",
        "",
        "## Summary",
        "",
        f"- Semantic parser entry points: `{semantic_parsers} / 141`",
        f"- Semantic observation parsers: `{semantic_observation} / 141`",
        f"- Semantic prefix parsers: `{semantic_prefix} / 141`",
        f"- Semantic decoded parsers: `{semantic_decoded} / 141`",
        f"- Fully domain-decoded semantic parsers: `{fully_domain_decoded} / 141`",
        "",
        "A semantic observation is a real parser entry point with a named slotted class, header identity, raw body preservation, declared-field metadata where available, and diagnostics that say full domain decoding is not implemented yet. Semantic decoded rows go further and expose decoded fixed-field domain structures. This avoids silent overclaiming while still giving every PDU a typed semantic surface.",
        "",
        "| DIS | PDU | Name | Semantic class | Level | Fully decoded |",
        "| ---: | ---: | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['protocol_version']} | {row['pdu_type']} | {row['standard_name']} | "
            f"`{row['semantic_class']}` | `{row['semantic_level']}` | "
            f"{'yes' if row['fully_domain_decoded'] else 'no'} |"
        )
    return "\n".join(lines) + "\n"


def outputs(dis6: Path, dis7: Path) -> dict[Path, str]:
    rows = semantic_rows(dis6, dis7)
    return {
        ROOT / "src" / "fastdis" / "semantic_pdus.py": generate_python(rows),
        ROOT / "generated" / "semantic_pdu_parser_manifest.json": generate_manifest(rows),
        ROOT / "docs" / "SEMANTIC_PDU_COVERAGE.md": generate_markdown(rows),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dis6", type=Path, default=DEFAULT_DIS6)
    parser.add_argument("--dis7", type=Path, default=DEFAULT_DIS7)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = outputs(args.dis6, args.dis7)
    if args.check:
        stale: list[Path] = []
        for path, content in rendered.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        if stale:
            print("stale generated semantic PDU parser artifacts:", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    rows = semantic_rows(args.dis6, args.dis7)
    print(
        "generated semantic PDU parsers "
        f"semantic_parsers={len(rows)} fully_domain_decoded={sum(1 for row in rows if row['fully_domain_decoded'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
