/* Generated by tools/generate_pdu_catalog.py. Do not edit manually. */
#ifndef FASTDIS_PDU_CATALOG_H
#define FASTDIS_PDU_CATALOG_H

#include "fastdis/fastdis.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct fastdis_pdu_catalog_entry_s {
    uint8_t protocol_version;
    uint8_t pdu_type;
    uint8_t protocol_family;
    const char* class_name;
    const char* name;
    const char* family_name;
    uint8_t has_body_decoder;
} fastdis_pdu_catalog_entry_t;

#define FASTDIS_PDU_TYPE_OTHER                               0u
#define FASTDIS_PDU_TYPE_ENTITY_STATE                        1u
#define FASTDIS_PDU_TYPE_FIRE                                2u
#define FASTDIS_PDU_TYPE_DETONATION                          3u
#define FASTDIS_PDU_TYPE_COLLISION                           4u
#define FASTDIS_PDU_TYPE_SERVICE_REQUEST                     5u
#define FASTDIS_PDU_TYPE_RESUPPLY_OFFER                      6u
#define FASTDIS_PDU_TYPE_RESUPPLY_RECEIVED                   7u
#define FASTDIS_PDU_TYPE_RESUPPLY_CANCEL                     8u
#define FASTDIS_PDU_TYPE_REPAIR_COMPLETE                     9u
#define FASTDIS_PDU_TYPE_REPAIR_RESPONSE                     10u
#define FASTDIS_PDU_TYPE_CREATE_ENTITY                       11u
#define FASTDIS_PDU_TYPE_REMOVE_ENTITY                       12u
#define FASTDIS_PDU_TYPE_START_RESUME                        13u
#define FASTDIS_PDU_TYPE_STOP_FREEZE                         14u
#define FASTDIS_PDU_TYPE_ACKNOWLEDGE                         15u
#define FASTDIS_PDU_TYPE_ACTION_REQUEST                      16u
#define FASTDIS_PDU_TYPE_ACTION_RESPONSE                     17u
#define FASTDIS_PDU_TYPE_DATA_QUERY                          18u
#define FASTDIS_PDU_TYPE_SET_DATA                            19u
#define FASTDIS_PDU_TYPE_DATA                                20u
#define FASTDIS_PDU_TYPE_EVENT_REPORT                        21u
#define FASTDIS_PDU_TYPE_COMMENT                             22u
#define FASTDIS_PDU_TYPE_ELECTRONIC_EMISSIONS                23u
#define FASTDIS_PDU_TYPE_DESIGNATOR                          24u
#define FASTDIS_PDU_TYPE_TRANSMITTER                         25u
#define FASTDIS_PDU_TYPE_SIGNAL                              26u
#define FASTDIS_PDU_TYPE_RECEIVER                            27u
#define FASTDIS_PDU_TYPE_IFF_ATC_NAV_AIDS_LAYER1             28u
#define FASTDIS_PDU_TYPE_IFF                                 28u
#define FASTDIS_PDU_TYPE_UA                                  29u
#define FASTDIS_PDU_TYPE_SEES                                30u
#define FASTDIS_PDU_TYPE_INTERCOM_SIGNAL                     31u
#define FASTDIS_PDU_TYPE_INTERCOM_CONTROL                    32u
#define FASTDIS_PDU_TYPE_AGGREGATE_STATE                     33u
#define FASTDIS_PDU_TYPE_IS_GROUP_OF                         34u
#define FASTDIS_PDU_TYPE_TRANSFER_CONTROL_REQUEST            35u
#define FASTDIS_PDU_TYPE_TRANSFER_OWNERSHIP                  35u
#define FASTDIS_PDU_TYPE_IS_PART_OF                          36u
#define FASTDIS_PDU_TYPE_MINEFIELD_STATE                     37u
#define FASTDIS_PDU_TYPE_MINEFIELD_QUERY                     38u
#define FASTDIS_PDU_TYPE_MINEFIELD_DATA                      39u
#define FASTDIS_PDU_TYPE_MINEFIELD_RESPONSE_NACK             40u
#define FASTDIS_PDU_TYPE_ENVIRONMENTAL_PROCESS               41u
#define FASTDIS_PDU_TYPE_GRIDDED_DATA                        42u
#define FASTDIS_PDU_TYPE_POINT_OBJECT_STATE                  43u
#define FASTDIS_PDU_TYPE_LINEAR_OBJECT_STATE                 44u
#define FASTDIS_PDU_TYPE_AREAL_OBJECT_STATE                  45u
#define FASTDIS_PDU_TYPE_TSPI                                46u
#define FASTDIS_PDU_TYPE_APPEARANCE                          47u
#define FASTDIS_PDU_TYPE_ARTICULATED_PARTS                   48u
#define FASTDIS_PDU_TYPE_LEFIRE                              49u
#define FASTDIS_PDU_TYPE_LEDETONATION                        50u
#define FASTDIS_PDU_TYPE_CREATE_ENTITY_RELIABLE              51u
#define FASTDIS_PDU_TYPE_REMOVE_ENTITY_RELIABLE              52u
#define FASTDIS_PDU_TYPE_START_RESUME_RELIABLE               53u
#define FASTDIS_PDU_TYPE_STOP_FREEZE_RELIABLE                54u
#define FASTDIS_PDU_TYPE_ACKNOWLEDGE_RELIABLE                55u
#define FASTDIS_PDU_TYPE_ACTION_REQUEST_RELIABLE             56u
#define FASTDIS_PDU_TYPE_ACTION_RESPONSE_RELIABLE            57u
#define FASTDIS_PDU_TYPE_DATA_QUERY_RELIABLE                 58u
#define FASTDIS_PDU_TYPE_SET_DATA_RELIABLE                   59u
#define FASTDIS_PDU_TYPE_DATA_RELIABLE                       60u
#define FASTDIS_PDU_TYPE_EVENT_REPORT_RELIABLE               61u
#define FASTDIS_PDU_TYPE_COMMENT_RELIABLE                    62u
#define FASTDIS_PDU_TYPE_RECORD_RELIABLE                     63u
#define FASTDIS_PDU_TYPE_SET_RECORD_RELIABLE                 64u
#define FASTDIS_PDU_TYPE_RECORD_QUERY_RELIABLE               65u
#define FASTDIS_PDU_TYPE_COLLISION_ELASTIC                   66u
#define FASTDIS_PDU_TYPE_ENTITY_STATE_UPDATE                 67u
#define FASTDIS_PDU_TYPE_DIRECTED_ENERGY_FIRE                68u
#define FASTDIS_PDU_TYPE_ENTITY_DAMAGE_STATUS                69u
#define FASTDIS_PDU_TYPE_INFORMATION_OPERATIONS_ACTION       70u
#define FASTDIS_PDU_TYPE_INFORMATION_OPERATIONS_REPORT       71u
#define FASTDIS_PDU_TYPE_ATTRIBUTE                           72u

#define FASTDIS_PDU_CATALOG_COUNT 141u

static const fastdis_pdu_catalog_entry_t FASTDIS_PDU_CATALOG[] = {
    {6u, 0u, 0u, "OtherPdu", "Other", "Protocol Family 0", 0u},
    {6u, 1u, 1u, "EntityStatePdu", "Entity State", "Entity Information", 1u},
    {6u, 2u, 2u, "FirePdu", "Fire", "Warfare", 1u},
    {6u, 3u, 2u, "DetonationPdu", "Detonation", "Warfare", 1u},
    {6u, 4u, 1u, "CollisionPdu", "Collision", "Entity Information", 1u},
    {6u, 5u, 3u, "ServiceRequestPdu", "Service Request", "Logistics", 0u},
    {6u, 6u, 3u, "ResupplyOfferPdu", "Resupply Offer", "Logistics", 0u},
    {6u, 7u, 3u, "ResupplyReceivedPdu", "Resupply Received", "Logistics", 0u},
    {6u, 8u, 3u, "ResupplyCancelPdu", "Resupply Cancel", "Logistics", 0u},
    {6u, 9u, 3u, "RepairCompletePdu", "Repair Complete", "Logistics", 0u},
    {6u, 10u, 3u, "RepairResponsePdu", "Repair Response", "Logistics", 0u},
    {6u, 11u, 5u, "CreateEntityPdu", "Create Entity", "Simulation Management", 1u},
    {6u, 12u, 5u, "RemoveEntityPdu", "Remove Entity", "Simulation Management", 1u},
    {6u, 13u, 5u, "StartResumePdu", "Start Resume", "Simulation Management", 1u},
    {6u, 14u, 5u, "StopFreezePdu", "Stop Freeze", "Simulation Management", 1u},
    {6u, 15u, 5u, "AcknowledgePdu", "Acknowledge", "Simulation Management", 0u},
    {6u, 16u, 5u, "ActionRequestPdu", "Action Request", "Simulation Management", 0u},
    {6u, 17u, 5u, "ActionResponsePdu", "Action Response", "Simulation Management", 0u},
    {6u, 18u, 5u, "DataQueryPdu", "Data Query", "Simulation Management", 0u},
    {6u, 19u, 5u, "SetDataPdu", "Set Data", "Simulation Management", 0u},
    {6u, 20u, 5u, "DataPdu", "Data", "Simulation Management", 0u},
    {6u, 21u, 5u, "EventReportPdu", "Event Report", "Simulation Management", 0u},
    {6u, 22u, 5u, "CommentPdu", "Comment", "Simulation Management", 0u},
    {6u, 23u, 6u, "ElectronicEmissionsPdu", "Electronic Emissions", "Distributed Emission Regeneration", 0u},
    {6u, 24u, 6u, "DesignatorPdu", "Designator", "Distributed Emission Regeneration", 0u},
    {6u, 25u, 4u, "TransmitterPdu", "Transmitter", "Radio Communications", 0u},
    {6u, 26u, 4u, "SignalPdu", "Signal", "Radio Communications", 0u},
    {6u, 27u, 4u, "ReceiverPdu", "Receiver", "Radio Communications", 0u},
    {6u, 28u, 6u, "IffAtcNavAidsLayer1Pdu", "Iff Atc Nav Aids Layer1", "Distributed Emission Regeneration", 0u},
    {6u, 29u, 6u, "UaPdu", "Ua", "Distributed Emission Regeneration", 0u},
    {6u, 30u, 6u, "SeesPdu", "Sees", "Distributed Emission Regeneration", 0u},
    {6u, 31u, 4u, "IntercomSignalPdu", "Intercom Signal", "Radio Communications", 0u},
    {6u, 32u, 4u, "IntercomControlPdu", "Intercom Control", "Radio Communications", 0u},
    {6u, 33u, 7u, "AggregateStatePdu", "Aggregate State", "Entity Management", 0u},
    {6u, 34u, 7u, "IsGroupOfPdu", "Is Group Of", "Entity Management", 0u},
    {6u, 35u, 7u, "TransferControlRequestPdu", "Transfer Control Request", "Entity Management", 0u},
    {6u, 36u, 7u, "IsPartOfPdu", "Is Part Of", "Entity Management", 0u},
    {6u, 37u, 8u, "MinefieldStatePdu", "Minefield State", "Minefield", 0u},
    {6u, 38u, 8u, "MinefieldQueryPdu", "Minefield Query", "Minefield", 0u},
    {6u, 39u, 8u, "MinefieldDataPdu", "Minefield Data", "Minefield", 0u},
    {6u, 40u, 8u, "MinefieldResponseNackPdu", "Minefield Response Nack", "Minefield", 0u},
    {6u, 41u, 9u, "EnvironmentalProcessPdu", "Environmental Process", "Synthetic Environment", 0u},
    {6u, 42u, 9u, "GriddedDataPdu", "Gridded Data", "Synthetic Environment", 0u},
    {6u, 43u, 9u, "PointObjectStatePdu", "Point Object State", "Synthetic Environment", 0u},
    {6u, 44u, 9u, "LinearObjectStatePdu", "Linear Object State", "Synthetic Environment", 0u},
    {6u, 45u, 9u, "ArealObjectStatePdu", "Areal Object State", "Synthetic Environment", 0u},
    {6u, 46u, 11u, "TSPIPdu", "T S P I", "Live Entity", 0u},
    {6u, 47u, 11u, "AppearancePdu", "Appearance", "Live Entity", 0u},
    {6u, 48u, 11u, "ArticulatedPartsPdu", "Articulated Parts", "Live Entity", 0u},
    {6u, 49u, 11u, "LEFirePdu", "L E Fire", "Live Entity", 0u},
    {6u, 50u, 11u, "LEDetonationPdu", "L E Detonation", "Live Entity", 0u},
    {6u, 51u, 10u, "CreateEntityReliablePdu", "Create Entity Reliable", "Simulation Management with Reliability", 0u},
    {6u, 52u, 10u, "RemoveEntityReliablePdu", "Remove Entity Reliable", "Simulation Management with Reliability", 0u},
    {6u, 53u, 10u, "StartResumeReliablePdu", "Start Resume Reliable", "Simulation Management with Reliability", 0u},
    {6u, 54u, 10u, "StopFreezeReliablePdu", "Stop Freeze Reliable", "Simulation Management with Reliability", 0u},
    {6u, 55u, 10u, "AcknowledgeReliablePdu", "Acknowledge Reliable", "Simulation Management with Reliability", 0u},
    {6u, 56u, 10u, "ActionRequestReliablePdu", "Action Request Reliable", "Simulation Management with Reliability", 0u},
    {6u, 57u, 10u, "ActionResponseReliablePdu", "Action Response Reliable", "Simulation Management with Reliability", 0u},
    {6u, 58u, 10u, "DataQueryReliablePdu", "Data Query Reliable", "Simulation Management with Reliability", 0u},
    {6u, 59u, 10u, "SetDataReliablePdu", "Set Data Reliable", "Simulation Management with Reliability", 0u},
    {6u, 60u, 10u, "DataReliablePdu", "Data Reliable", "Simulation Management with Reliability", 0u},
    {6u, 61u, 10u, "EventReportReliablePdu", "Event Report Reliable", "Simulation Management with Reliability", 0u},
    {6u, 62u, 10u, "CommentReliablePdu", "Comment Reliable", "Simulation Management with Reliability", 0u},
    {6u, 63u, 10u, "RecordReliablePdu", "Record Reliable", "Simulation Management with Reliability", 0u},
    {6u, 64u, 10u, "SetRecordReliablePdu", "Set Record Reliable", "Simulation Management with Reliability", 0u},
    {6u, 65u, 10u, "RecordQueryReliablePdu", "Record Query Reliable", "Simulation Management with Reliability", 0u},
    {6u, 66u, 1u, "CollisionElasticPdu", "Collision Elastic", "Entity Information", 1u},
    {6u, 67u, 1u, "EntityStateUpdatePdu", "Entity State Update", "Entity Information", 1u},
    {7u, 0u, 0u, "OtherPdu", "Other", "Protocol Family 0", 0u},
    {7u, 1u, 1u, "EntityStatePdu", "Entity State", "Entity Information", 1u},
    {7u, 2u, 2u, "FirePdu", "Fire", "Warfare", 1u},
    {7u, 3u, 2u, "DetonationPdu", "Detonation", "Warfare", 1u},
    {7u, 4u, 1u, "CollisionPdu", "Collision", "Entity Information", 1u},
    {7u, 5u, 3u, "ServiceRequestPdu", "Service Request", "Logistics", 0u},
    {7u, 6u, 3u, "ResupplyOfferPdu", "Resupply Offer", "Logistics", 0u},
    {7u, 7u, 3u, "ResupplyReceivedPdu", "Resupply Received", "Logistics", 0u},
    {7u, 8u, 3u, "ResupplyCancelPdu", "Resupply Cancel", "Logistics", 0u},
    {7u, 9u, 3u, "RepairCompletePdu", "Repair Complete", "Logistics", 0u},
    {7u, 10u, 3u, "RepairResponsePdu", "Repair Response", "Logistics", 0u},
    {7u, 11u, 5u, "CreateEntityPdu", "Create Entity", "Simulation Management", 1u},
    {7u, 12u, 5u, "RemoveEntityPdu", "Remove Entity", "Simulation Management", 1u},
    {7u, 13u, 5u, "StartResumePdu", "Start Resume", "Simulation Management", 1u},
    {7u, 14u, 5u, "StopFreezePdu", "Stop Freeze", "Simulation Management", 1u},
    {7u, 15u, 5u, "AcknowledgePdu", "Acknowledge", "Simulation Management", 0u},
    {7u, 16u, 5u, "ActionRequestPdu", "Action Request", "Simulation Management", 0u},
    {7u, 17u, 5u, "ActionResponsePdu", "Action Response", "Simulation Management", 0u},
    {7u, 18u, 5u, "DataQueryPdu", "Data Query", "Simulation Management", 0u},
    {7u, 19u, 5u, "SetDataPdu", "Set Data", "Simulation Management", 0u},
    {7u, 20u, 5u, "DataPdu", "Data", "Simulation Management", 0u},
    {7u, 21u, 5u, "EventReportPdu", "Event Report", "Simulation Management", 0u},
    {7u, 22u, 5u, "CommentPdu", "Comment", "Simulation Management", 0u},
    {7u, 23u, 6u, "ElectronicEmissionsPdu", "Electronic Emissions", "Distributed Emission Regeneration", 0u},
    {7u, 24u, 6u, "DesignatorPdu", "Designator", "Distributed Emission Regeneration", 0u},
    {7u, 25u, 4u, "TransmitterPdu", "Transmitter", "Radio Communications", 0u},
    {7u, 26u, 4u, "SignalPdu", "Signal", "Radio Communications", 0u},
    {7u, 27u, 4u, "ReceiverPdu", "Receiver", "Radio Communications", 0u},
    {7u, 28u, 6u, "IffPdu", "Iff", "Distributed Emission Regeneration", 0u},
    {7u, 29u, 6u, "UaPdu", "Ua", "Distributed Emission Regeneration", 0u},
    {7u, 30u, 6u, "SeesPdu", "Sees", "Distributed Emission Regeneration", 0u},
    {7u, 31u, 4u, "IntercomSignalPdu", "Intercom Signal", "Radio Communications", 0u},
    {7u, 32u, 4u, "IntercomControlPdu", "Intercom Control", "Radio Communications", 0u},
    {7u, 33u, 7u, "AggregateStatePdu", "Aggregate State", "Entity Management", 0u},
    {7u, 34u, 7u, "IsGroupOfPdu", "Is Group Of", "Entity Management", 0u},
    {7u, 35u, 7u, "TransferOwnershipPdu", "Transfer Ownership", "Entity Management", 0u},
    {7u, 36u, 7u, "IsPartOfPdu", "Is Part Of", "Entity Management", 0u},
    {7u, 37u, 8u, "MinefieldStatePdu", "Minefield State", "Minefield", 0u},
    {7u, 38u, 8u, "MinefieldQueryPdu", "Minefield Query", "Minefield", 0u},
    {7u, 39u, 8u, "MinefieldDataPdu", "Minefield Data", "Minefield", 0u},
    {7u, 40u, 8u, "MinefieldResponseNackPdu", "Minefield Response Nack", "Minefield", 0u},
    {7u, 41u, 9u, "EnvironmentalProcessPdu", "Environmental Process", "Synthetic Environment", 0u},
    {7u, 42u, 9u, "GriddedDataPdu", "Gridded Data", "Synthetic Environment", 0u},
    {7u, 43u, 9u, "PointObjectStatePdu", "Point Object State", "Synthetic Environment", 0u},
    {7u, 44u, 9u, "LinearObjectStatePdu", "Linear Object State", "Synthetic Environment", 0u},
    {7u, 45u, 9u, "ArealObjectStatePdu", "Areal Object State", "Synthetic Environment", 0u},
    {7u, 46u, 11u, "TSPIPdu", "T S P I", "Live Entity", 0u},
    {7u, 47u, 11u, "AppearancePdu", "Appearance", "Live Entity", 0u},
    {7u, 48u, 11u, "ArticulatedPartsPdu", "Articulated Parts", "Live Entity", 0u},
    {7u, 49u, 11u, "LEFirePdu", "L E Fire", "Live Entity", 0u},
    {7u, 50u, 11u, "LEDetonationPdu", "L E Detonation", "Live Entity", 0u},
    {7u, 51u, 10u, "CreateEntityReliablePdu", "Create Entity Reliable", "Simulation Management with Reliability", 0u},
    {7u, 52u, 10u, "RemoveEntityReliablePdu", "Remove Entity Reliable", "Simulation Management with Reliability", 0u},
    {7u, 53u, 10u, "StartResumeReliablePdu", "Start Resume Reliable", "Simulation Management with Reliability", 0u},
    {7u, 54u, 10u, "StopFreezeReliablePdu", "Stop Freeze Reliable", "Simulation Management with Reliability", 0u},
    {7u, 55u, 10u, "AcknowledgeReliablePdu", "Acknowledge Reliable", "Simulation Management with Reliability", 0u},
    {7u, 56u, 10u, "ActionRequestReliablePdu", "Action Request Reliable", "Simulation Management with Reliability", 0u},
    {7u, 57u, 10u, "ActionResponseReliablePdu", "Action Response Reliable", "Simulation Management with Reliability", 0u},
    {7u, 58u, 10u, "DataQueryReliablePdu", "Data Query Reliable", "Simulation Management with Reliability", 0u},
    {7u, 59u, 10u, "SetDataReliablePdu", "Set Data Reliable", "Simulation Management with Reliability", 0u},
    {7u, 60u, 10u, "DataReliablePdu", "Data Reliable", "Simulation Management with Reliability", 0u},
    {7u, 61u, 10u, "EventReportReliablePdu", "Event Report Reliable", "Simulation Management with Reliability", 0u},
    {7u, 62u, 10u, "CommentReliablePdu", "Comment Reliable", "Simulation Management with Reliability", 0u},
    {7u, 63u, 10u, "RecordReliablePdu", "Record Reliable", "Simulation Management with Reliability", 0u},
    {7u, 64u, 10u, "SetRecordReliablePdu", "Set Record Reliable", "Simulation Management with Reliability", 0u},
    {7u, 65u, 10u, "RecordQueryReliablePdu", "Record Query Reliable", "Simulation Management with Reliability", 0u},
    {7u, 66u, 1u, "CollisionElasticPdu", "Collision Elastic", "Entity Information", 1u},
    {7u, 67u, 1u, "EntityStateUpdatePdu", "Entity State Update", "Entity Information", 1u},
    {7u, 68u, 2u, "DirectedEnergyFirePdu", "Directed Energy Fire", "Warfare", 0u},
    {7u, 69u, 2u, "EntityDamageStatusPdu", "Entity Damage Status", "Warfare", 0u},
    {7u, 70u, 13u, "InformationOperationsActionPdu", "Information Operations Action", "Information Operations", 0u},
    {7u, 71u, 13u, "InformationOperationsReportPdu", "Information Operations Report", "Information Operations", 0u},
    {7u, 72u, 1u, "AttributePdu", "Attribute", "Entity Information", 0u},
};

static inline const fastdis_pdu_catalog_entry_t* fastdis_pdu_catalog_find(uint8_t protocol_version, uint8_t pdu_type) {
    for (uint32_t i = 0; i < FASTDIS_PDU_CATALOG_COUNT; ++i) {
        const fastdis_pdu_catalog_entry_t* entry = &FASTDIS_PDU_CATALOG[i];
        if (entry->protocol_version == protocol_version && entry->pdu_type == pdu_type) {
            return entry;
        }
    }
    return 0;
}

#ifdef __cplusplus
}
#endif

#endif /* FASTDIS_PDU_CATALOG_H */
